/*
 * JumpCloud APIs
 *  JumpCloud's V1 API. This set of endpoints allows JumpCloud customers to manage commands, systems, & system users.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Applicationtemplate;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Applicationtemplateslist
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-12-09T23:53:52.741Z")
public class Applicationtemplateslist {
  @SerializedName("results")
  private List<Applicationtemplate> results = null;

  @SerializedName("totalCount")
  private Integer totalCount = null;

  public Applicationtemplateslist results(List<Applicationtemplate> results) {
    this.results = results;
    return this;
  }

  public Applicationtemplateslist addResultsItem(Applicationtemplate resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<Applicationtemplate>();
    }
    this.results.add(resultsItem);
    return this;
  }

   /**
   * The list of applications.
   * @return results
  **/
  @ApiModelProperty(value = "The list of applications.")
  public List<Applicationtemplate> getResults() {
    return results;
  }

  public void setResults(List<Applicationtemplate> results) {
    this.results = results;
  }

  public Applicationtemplateslist totalCount(Integer totalCount) {
    this.totalCount = totalCount;
    return this;
  }

   /**
   * The total number of applications.
   * @return totalCount
  **/
  @ApiModelProperty(value = "The total number of applications.")
  public Integer getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(Integer totalCount) {
    this.totalCount = totalCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Applicationtemplateslist applicationtemplateslist = (Applicationtemplateslist) o;
    return Objects.equals(this.results, applicationtemplateslist.results) &&
        Objects.equals(this.totalCount, applicationtemplateslist.totalCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(results, totalCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Applicationtemplateslist {\n");
    
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

