/*
 * JumpCloud APIs
 *  JumpCloud's V1 API. This set of endpoints allows JumpCloud customers to manage commands, systems, & system users.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Fde
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-12T20:59:54.768Z")
public class Fde {
  @SerializedName("keyPresent")
  private Boolean keyPresent = null;

  public Fde keyPresent(Boolean keyPresent) {
    this.keyPresent = keyPresent;
    return this;
  }

   /**
   * Get keyPresent
   * @return keyPresent
  **/
  @ApiModelProperty(value = "")
  public Boolean isKeyPresent() {
    return keyPresent;
  }

  public void setKeyPresent(Boolean keyPresent) {
    this.keyPresent = keyPresent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Fde fde = (Fde) o;
    return Objects.equals(this.keyPresent, fde.keyPresent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keyPresent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Fde {\n");
    
    sb.append("    keyPresent: ").append(toIndentedString(keyPresent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

