/*
 * JumpCloud APIs
 * V1 & V2 versions of JumpCloud's API. The previous version of JumpCloud's API. This set of endpoints allows JumpCloud customers to manage commands, systems, & system users.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse200ConfigIdpEntityIdTooltipVariables;
import java.io.IOException;

/**
 * InlineResponse200ConfigIdpEntityIdTooltip
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-08T19:04:49.654Z")
public class InlineResponse200ConfigIdpEntityIdTooltip {
  @SerializedName("template")
  private String template = null;

  @SerializedName("variables")
  private InlineResponse200ConfigIdpEntityIdTooltipVariables variables = null;

  public InlineResponse200ConfigIdpEntityIdTooltip template(String template) {
    this.template = template;
    return this;
  }

   /**
   * Get template
   * @return template
  **/
  @ApiModelProperty(value = "")
  public String getTemplate() {
    return template;
  }

  public void setTemplate(String template) {
    this.template = template;
  }

  public InlineResponse200ConfigIdpEntityIdTooltip variables(InlineResponse200ConfigIdpEntityIdTooltipVariables variables) {
    this.variables = variables;
    return this;
  }

   /**
   * Get variables
   * @return variables
  **/
  @ApiModelProperty(value = "")
  public InlineResponse200ConfigIdpEntityIdTooltipVariables getVariables() {
    return variables;
  }

  public void setVariables(InlineResponse200ConfigIdpEntityIdTooltipVariables variables) {
    this.variables = variables;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200ConfigIdpEntityIdTooltip inlineResponse200ConfigIdpEntityIdTooltip = (InlineResponse200ConfigIdpEntityIdTooltip) o;
    return Objects.equals(this.template, inlineResponse200ConfigIdpEntityIdTooltip.template) &&
        Objects.equals(this.variables, inlineResponse200ConfigIdpEntityIdTooltip.variables);
  }

  @Override
  public int hashCode() {
    return Objects.hash(template, variables);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200ConfigIdpEntityIdTooltip {\n");
    
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

