/*
 * JumpCloud APIs
 *  JumpCloud's V1 API. This set of endpoints allows JumpCloud customers to manage commands, systems, & system users.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Tag;
import io.swagger.client.model.Tagpost;
import io.swagger.client.model.Tagput;
import io.swagger.client.model.Tagslist;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TagsApi
 */
@Ignore
public class TagsApiTest {

    private final TagsApi api = new TagsApi();

    
    /**
     * Delete a Tag
     *
     * Hidden as Tags is deprecated  Delete a Tag.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void tagsDeleteTest() throws ApiException {
        String name = null;
        String contentType = null;
        String accept = null;
        Tag response = api.tagsDelete(name, contentType, accept);

        // TODO: test validations
    }
    
    /**
     * List a Tag
     *
     * Hidden as Tags is deprecated  Returns a specific tag.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void tagsGetTest() throws ApiException {
        String name = null;
        String contentType = null;
        String accept = null;
        String fields = null;
        Integer limit = null;
        Integer skip = null;
        String sort = null;
        String filter = null;
        Tag response = api.tagsGet(name, contentType, accept, fields, limit, skip, sort, filter);

        // TODO: test validations
    }
    
    /**
     * List All Tags
     *
     * Hidden as Tags is deprecated  Returns all Tags.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void tagsListTest() throws ApiException {
        String contentType = null;
        String accept = null;
        String fields = null;
        Integer limit = null;
        Integer skip = null;
        String sort = null;
        String filter = null;
        Tagslist response = api.tagsList(contentType, accept, fields, limit, skip, sort, filter);

        // TODO: test validations
    }
    
    /**
     * Create a Tag
     *
     * Hidden as Tags is deprecated  Create a tag.  ### Examples #### Create a new Tag  &#x60;&#x60;&#x60; curl \\   -d &#39;{\&quot;name\&quot; : \&quot;Developers\&quot;}&#39; \\   -X &#39;POST&#39; \\   -H &#39;Content-Type: application/json&#39; \\   -H &#39;Accept: application/json&#39; \\   -H \&quot;x-api-key: [YOUR_API_KEY_HERE]\&quot; \\   \&quot;https://console.jumpcloud.com/api/tags\&quot; &#x60;&#x60;&#x60;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void tagsPostTest() throws ApiException {
        String contentType = null;
        String accept = null;
        Tagpost body = null;
        Tag response = api.tagsPost(contentType, accept, body);

        // TODO: test validations
    }
    
    /**
     * Update a Tag
     *
     * Hidden as Tags is deprecated  Update a specific tag.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void tagsPutTest() throws ApiException {
        String name = null;
        String contentType = null;
        String accept = null;
        Tagput body = null;
        Tag response = api.tagsPut(name, contentType, accept, body);

        // TODO: test validations
    }
    
}
