/*
 * JumpCloud APIs
 *  JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AppleMDM;
import java.io.IOException;

/**
 * InlineResponse201
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-21T20:17:34.763Z")
public class InlineResponse201 {
  @SerializedName("appleMdm")
  private AppleMDM appleMdm = null;

  @SerializedName("signedCsrPlist")
  private String signedCsrPlist = null;

  public InlineResponse201 appleMdm(AppleMDM appleMdm) {
    this.appleMdm = appleMdm;
    return this;
  }

   /**
   * Get appleMdm
   * @return appleMdm
  **/
  @ApiModelProperty(value = "")
  public AppleMDM getAppleMdm() {
    return appleMdm;
  }

  public void setAppleMdm(AppleMDM appleMdm) {
    this.appleMdm = appleMdm;
  }

  public InlineResponse201 signedCsrPlist(String signedCsrPlist) {
    this.signedCsrPlist = signedCsrPlist;
    return this;
  }

   /**
   * Get signedCsrPlist
   * @return signedCsrPlist
  **/
  @ApiModelProperty(value = "")
  public String getSignedCsrPlist() {
    return signedCsrPlist;
  }

  public void setSignedCsrPlist(String signedCsrPlist) {
    this.signedCsrPlist = signedCsrPlist;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse201 inlineResponse201 = (InlineResponse201) o;
    return Objects.equals(this.appleMdm, inlineResponse201.appleMdm) &&
        Objects.equals(this.signedCsrPlist, inlineResponse201.signedCsrPlist);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appleMdm, signedCsrPlist);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse201 {\n");
    
    sb.append("    appleMdm: ").append(toIndentedString(appleMdm)).append("\n");
    sb.append("    signedCsrPlist: ").append(toIndentedString(signedCsrPlist)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

