/*
 * JumpCloud APIs
 *  JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SystemInsightsShadow
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-12-09T23:54:01.559Z")
public class SystemInsightsShadow {
  @SerializedName("collection_time")
  private String collectionTime = null;

  @SerializedName("expire")
  private String expire = null;

  @SerializedName("flag")
  private String flag = null;

  @SerializedName("hash_alg")
  private String hashAlg = null;

  @SerializedName("inactive")
  private String inactive = null;

  @SerializedName("last_change")
  private String lastChange = null;

  @SerializedName("max")
  private String max = null;

  @SerializedName("min	")
  private String min = null;

  @SerializedName("password_status")
  private String passwordStatus = null;

  @SerializedName("system_id")
  private String systemId = null;

  @SerializedName("username")
  private String username = null;

  @SerializedName("warning")
  private String warning = null;

  public SystemInsightsShadow collectionTime(String collectionTime) {
    this.collectionTime = collectionTime;
    return this;
  }

   /**
   * Get collectionTime
   * @return collectionTime
  **/
  @ApiModelProperty(value = "")
  public String getCollectionTime() {
    return collectionTime;
  }

  public void setCollectionTime(String collectionTime) {
    this.collectionTime = collectionTime;
  }

  public SystemInsightsShadow expire(String expire) {
    this.expire = expire;
    return this;
  }

   /**
   * Get expire
   * @return expire
  **/
  @ApiModelProperty(value = "")
  public String getExpire() {
    return expire;
  }

  public void setExpire(String expire) {
    this.expire = expire;
  }

  public SystemInsightsShadow flag(String flag) {
    this.flag = flag;
    return this;
  }

   /**
   * Get flag
   * @return flag
  **/
  @ApiModelProperty(value = "")
  public String getFlag() {
    return flag;
  }

  public void setFlag(String flag) {
    this.flag = flag;
  }

  public SystemInsightsShadow hashAlg(String hashAlg) {
    this.hashAlg = hashAlg;
    return this;
  }

   /**
   * Get hashAlg
   * @return hashAlg
  **/
  @ApiModelProperty(value = "")
  public String getHashAlg() {
    return hashAlg;
  }

  public void setHashAlg(String hashAlg) {
    this.hashAlg = hashAlg;
  }

  public SystemInsightsShadow inactive(String inactive) {
    this.inactive = inactive;
    return this;
  }

   /**
   * Get inactive
   * @return inactive
  **/
  @ApiModelProperty(value = "")
  public String getInactive() {
    return inactive;
  }

  public void setInactive(String inactive) {
    this.inactive = inactive;
  }

  public SystemInsightsShadow lastChange(String lastChange) {
    this.lastChange = lastChange;
    return this;
  }

   /**
   * Get lastChange
   * @return lastChange
  **/
  @ApiModelProperty(value = "")
  public String getLastChange() {
    return lastChange;
  }

  public void setLastChange(String lastChange) {
    this.lastChange = lastChange;
  }

  public SystemInsightsShadow max(String max) {
    this.max = max;
    return this;
  }

   /**
   * Get max
   * @return max
  **/
  @ApiModelProperty(value = "")
  public String getMax() {
    return max;
  }

  public void setMax(String max) {
    this.max = max;
  }

  public SystemInsightsShadow min(String min) {
    this.min = min;
    return this;
  }

   /**
   * Get min
   * @return min
  **/
  @ApiModelProperty(value = "")
  public String getMin() {
    return min;
  }

  public void setMin(String min) {
    this.min = min;
  }

  public SystemInsightsShadow passwordStatus(String passwordStatus) {
    this.passwordStatus = passwordStatus;
    return this;
  }

   /**
   * Get passwordStatus
   * @return passwordStatus
  **/
  @ApiModelProperty(value = "")
  public String getPasswordStatus() {
    return passwordStatus;
  }

  public void setPasswordStatus(String passwordStatus) {
    this.passwordStatus = passwordStatus;
  }

  public SystemInsightsShadow systemId(String systemId) {
    this.systemId = systemId;
    return this;
  }

   /**
   * Get systemId
   * @return systemId
  **/
  @ApiModelProperty(value = "")
  public String getSystemId() {
    return systemId;
  }

  public void setSystemId(String systemId) {
    this.systemId = systemId;
  }

  public SystemInsightsShadow username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @ApiModelProperty(value = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public SystemInsightsShadow warning(String warning) {
    this.warning = warning;
    return this;
  }

   /**
   * Get warning
   * @return warning
  **/
  @ApiModelProperty(value = "")
  public String getWarning() {
    return warning;
  }

  public void setWarning(String warning) {
    this.warning = warning;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SystemInsightsShadow systemInsightsShadow = (SystemInsightsShadow) o;
    return Objects.equals(this.collectionTime, systemInsightsShadow.collectionTime) &&
        Objects.equals(this.expire, systemInsightsShadow.expire) &&
        Objects.equals(this.flag, systemInsightsShadow.flag) &&
        Objects.equals(this.hashAlg, systemInsightsShadow.hashAlg) &&
        Objects.equals(this.inactive, systemInsightsShadow.inactive) &&
        Objects.equals(this.lastChange, systemInsightsShadow.lastChange) &&
        Objects.equals(this.max, systemInsightsShadow.max) &&
        Objects.equals(this.min, systemInsightsShadow.min) &&
        Objects.equals(this.passwordStatus, systemInsightsShadow.passwordStatus) &&
        Objects.equals(this.systemId, systemInsightsShadow.systemId) &&
        Objects.equals(this.username, systemInsightsShadow.username) &&
        Objects.equals(this.warning, systemInsightsShadow.warning);
  }

  @Override
  public int hashCode() {
    return Objects.hash(collectionTime, expire, flag, hashAlg, inactive, lastChange, max, min, passwordStatus, systemId, username, warning);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SystemInsightsShadow {\n");
    
    sb.append("    collectionTime: ").append(toIndentedString(collectionTime)).append("\n");
    sb.append("    expire: ").append(toIndentedString(expire)).append("\n");
    sb.append("    flag: ").append(toIndentedString(flag)).append("\n");
    sb.append("    hashAlg: ").append(toIndentedString(hashAlg)).append("\n");
    sb.append("    inactive: ").append(toIndentedString(inactive)).append("\n");
    sb.append("    lastChange: ").append(toIndentedString(lastChange)).append("\n");
    sb.append("    max: ").append(toIndentedString(max)).append("\n");
    sb.append("    min: ").append(toIndentedString(min)).append("\n");
    sb.append("    passwordStatus: ").append(toIndentedString(passwordStatus)).append("\n");
    sb.append("    systemId: ").append(toIndentedString(systemId)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    warning: ").append(toIndentedString(warning)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

